SELECT ACCOUNT.`CUST_ID`, SUM(`AVAIL_BALANCE`) AS Total, `FIRST_NAME`, `LAST_NAME`, `BIRTH_DATE`, `OPEN_BRANCH_ID`, BRANCH.`NAME`, BRANCH.`ADDRESS`
FROM ACCOUNT 
JOIN INDIVIDUAL ON INDIVIDUAL.`CUST_ID` = ACCOUNT.`CUST_ID`
JOIN BRANCH ON BRANCH.`BRANCH_ID` = ACCOUNT.`OPEN_BRANCH_ID`
GROUP BY ACCOUNT.`CUST_ID`, ACCOUNT.`OPEN_BRANCH_ID`;