Select SUM(AVAIL_BALANCE) AS TOTAL, CUST_ID FROM ACCOUNT GROUP BY CUST_ID HAVING TOTAL>3000

SELECT SUM(AVAIL_BALANCE) AS Total, ACCOUNT.`CUST_ID`, `FIRST_NAME`, `LAST_NAME`
FROM ACCOUNT, INDIVIDUAL
WHERE ACCOUNT.`CUST_ID` = INDIVIDUAL.`CUST_ID`
GROUP BY `CUST_ID`
HAVING Total>3000;
